#!/bin/bash

if [ ! -d "./Contacts" ]
  then
    mkdir Contacts
fi

while getopts ":ard" opt; do
  case ${opt} in
    a ) echo "Please enter a name: "
        read name
        echo "Please enter an address: "
        read address
        echo "Please enter an email address: "
        read email
        echo "Please enter a phone number: "
        read phone
        echo "Name: $name
Address: $address
Email: $email
Phone Number: $phone" > "./Contacts/$name"
        echo "Contact added."
      ;;
    r ) echo "Please enter the name of the contact you want to remove: "
        read rmname
        rm "./Contacts/$rmname"
        echo "Contact removed."
      ;;
    d ) echo "please enter the name of hte contact you would like to view: "
        read vwname
        while IFS= read -r line
          do
            echo $line
          done < "./Contacts/$vwname"
      ;;
    \? ) echo "Usage: cmd [-a] [-r] [-d]"
      ;;
  esac
done

