#!/bin/bash

# Display links on a webpage
# Usage: links file [option]
# Option: -f writes the output to a file

url="$2"

newFile="pageLinks"

wget -O $newFile $url

while getopts ":f" opt; do
  case ${opt} in
    f ) grep -Po '(?<=href=")(https)[^"]*' $newFile > links_file
      ;;
    \? ) echo "Usage: cmd [-f] [url]"
      ;;
  esac
done
rm $newFile

