#!/bin/bash

# Display links on a webpage
# Usage: links file [option]
# Option: -f writes the output to a file

url="$2"

newFile="pageLinks"

while getopts ":f:h" opt; do
  case ${opt} in
    f ) wget -O $newFile $url 
    grep -Po '(?<=href=")(https)[^"]*' $newFile > links_file
    rm $newFile
    echo "Write successful."
      ;;
    h ) echo "Usage: cmd [-f] [url]"
      ;;
    \? ) echo "Usage: cmd [-f] [url]"
      ;;
  esac
done

