#!/bin/bash

input="$2"
number=0

while getopts ":n:h" opt; do
  case ${opt} in
    n ) 
      while IFS= read -r line
        do
          ((number +=1))
          echo "${number}. $line"
        done < "$input"
      ;;
    h ) echo "Usage: cmd [-n] [file]"
      ;;
    \? ) echo "Usage: cmd [-n] [file]"
      ;;
  esac
done
